# docker-compose.yml
services:
  fragments:
    image: ${DOCKER_REPO}:${DOCKER_TAG}
    init: true
    ports:
      - '80:8080'
    environment:
      - NODE_ENV=production
      # Use whatever LOG_LEVEL is set to, or `info` as a default if not set
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # Allow the following variables to be forwarded into the container from the env if set
      - AWS_COGNITO_POOL_ID
      - AWS_COGNITO_CLIENT_ID
      - HTPASSWD
